FROM alpine:3.20

LABEL org.opencontainers.image.title="Vectora Asset Library"
LABEL org.opencontainers.image.description="Vectora asset library image scaffold."

WORKDIR /workspace/vectora-asset-library

COPY . /workspace/vectora-asset-library

CMD ["sh"]
